###
curl --location 'http://127.0.0.1:5000/recommend_jobs' \
--header 'Content-Type: application/json' \
--data '{
    "name": "Jane Doe",
    "skills": [
        "Python",
        "Java",
        "Hibernate"
    ],
    "experience_level": "Senior",
    "preferences": {
        "desired_roles": [
            "Python Developer",
            "Software Engineer"
        ],
        "locations": [
            "Remotes",
            "New Yorks"
        ],
        "job_type": "Full-Time"
    }
}'